# Generated by Django 5.2.4 on 2025-07-08 04:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nama Lengkap')),
                ('user_type', models.CharField(choices=[('super_admin', 'SUPER ADMIN'), ('dosen', 'USER DOSEN'), ('mahasiswa', 'USER MAHASISWA')], default='mahasiswa', max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/%Y/%m/')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('program_studi', models.CharField(blank=True, choices=[('Program Studi Bisnis Digital', 'Program Studi Bisnis Digital')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'All User',
                'verbose_name_plural': 'All User',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIP')),
                ('jabatan_akademik', models.CharField(blank=True, choices=[('Asisten Ahli', 'Asisten Ahli'), ('Lektor', 'Lektor'), ('Lektor Kepala', 'Lektor Kepala'), ('Profesor', 'Profesor')], max_length=50)),
                ('pendidikan_terakhir', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], default='S2', max_length=10)),
                ('bidang_keahlian', models.CharField(blank=True, max_length=100)),
                ('status_kepegawaian', models.CharField(choices=[('PNS', 'PNS'), ('Non-PNS', 'Non-PNS'), ('Kontrak', 'Kontrak')], default='PNS', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dosen_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Dosen',
                'verbose_name_plural': 'User Dosen',
            },
        ),
        migrations.CreateModel(
            name='UserMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='NIM')),
                ('angkatan', models.CharField(max_length=4)),
                ('semester', models.PositiveIntegerField(default=1)),
                ('kelas', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('Aktif', 'Aktif'), ('Cuti', 'Cuti'), ('Non-Aktif', 'Non-Aktif'), ('Lulus', 'Lulus'), ('DO', 'Drop Out')], default='Aktif', max_length=20)),
                ('ipk', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('tanggal_masuk', models.DateField()),
                ('dosen_wali', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mahasiswa_bimbingan', to='app.userdosen')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'mahasiswa'}, on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Mahasiswa',
                'verbose_name_plural': 'User Mahasiswa',
                'ordering': ['angkatan', 'kelas', 'nim'],
            },
        ),
    ]
